# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ab6fb206a78817b4691787a6ecff4fb3f6637051292016f89a94a93c5dd6e142dca3575f9954c4ef053a8d220b370efd545ccc8bff068a8033df01b627661a0

test:
  secret_key_base: e6fd7bf6698edbd5f3bdf9ba2635532e8e043a8c1e760ffc5526b5feb41fcf82efe3c7970bb72076b7abd0f9ccc8ad2595851070004720f56346576b6ab66cb4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
